version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: iot-survey-pga-db
    restart: always
    env_file:
      - .env.db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - rizki-app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: rizkiardianto/iot-pga-survey-be
    container_name: iot-survey-pga-be
    restart: always
    ports:
      - '5000:3000'
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
    networks:
      - rizki-app-network
    volumes:
      - ./logs:/app/logs
  
  # redis:
  #   image: redis:7-alpine
  #   container_name: survey_redis
  #   restart: unless-stopped
  #   ports:
  #     - "${REDIS_PORT}:6379"
  #   networks:
  #     - rizki-app-network
      
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - rizki-app-network

networks:
  app-network:
    external: true

volumes:
  dbdata:
    driver: local
  node_modules:
    driver: local